POST localhost:8081/mongo/add?firstName=Alexander&lastName=Ambroziak

###
GET localhost:8081/mongo/findFirstName?firstName=Alexander

###
GET localhost:8081/mongo/findFirstName?firstName=Artur

###
GET localhost:8081/mongo/findLastName?lastName=Ambroziak

###